# **CLASSIFICATION**

In [45]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.svm import SVC

In [24]:
#For more information about the dataset visit: https://archive.ics.uci.edu/dataset/451/breast+cancer+coimbra
cancer_dataset = pd.read_csv(r"C:\Users\Admin\Documents\ML_XL\dataR2.csv")
cancer_dataset

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   
114   72  25.590000       82    2.820  0.570392  24.9600    33.750000   
115   86  27.180000      138   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  Classification  
0     7.99585  417.114               1  
1     4.06405  468.786               1  
2     9.27715  554.697               1  
3    12.76600  928.220               1  
4    10.57635  773.920               1  
..        ...      ...             ...  
111  10.96000  268.230               2  
112   7.32000  330.160               2  
113  10.33000  314.050               2  
114   3.27000  392.460               2  
115   4.35000   90.090               2  

[116 rows x 10 columns]

In [25]:
cancer_dataset.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [26]:
cancer_dataset.tail()

Age    BMI  Glucose  Insulin      HOMA  Leptin  Adiponectin  Resistin  \
111   45  26.85       92     3.33  0.755688   54.68        12.10     10.96   
112   62  26.84      100     4.53  1.117400   12.45        21.42      7.32   
113   65  32.05       97     5.73  1.370998   61.48        22.54     10.33   
114   72  25.59       82     2.82  0.570392   24.96        33.75      3.27   
115   86  27.18      138    19.91  6.777364   90.28        14.11      4.35   

      MCP.1  Classification  
111  268.23               2  
112  330.16               2  
113  314.05               2  
114  392.46               2  
115   90.09               2

In [27]:

X = cancer_dataset.drop('Classification', axis=1)
y = cancer_dataset['Classification']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
#Write Code for Logistic Regression here

model = LogisticRegression()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion)

report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

Accuracy: 0.875
Confusion Matrix:
 [[11  1]
 [ 2 10]]
Classification Report:
               precision    recall  f1-score   support

           1       0.85      0.92      0.88        12
           2       0.91      0.83      0.87        12

    accuracy                           0.88        24
   macro avg       0.88      0.88      0.87        24
weighted avg       0.88      0.88      0.87        24



Linear Regression

SVM(Support Vector Machines)



---



In [29]:
#Write Code for SVM here

svm_model = SVC(kernel='linear')  

svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion)

report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


Accuracy: 0.7916666666666666
Confusion Matrix:
 [[11  1]
 [ 4  8]]
Classification Report:
               precision    recall  f1-score   support

           1       0.73      0.92      0.81        12
           2       0.89      0.67      0.76        12

    accuracy                           0.79        24
   macro avg       0.81      0.79      0.79        24
weighted avg       0.81      0.79      0.79        24



# **LINEAR REGRESSION**

In [35]:
#For more information for the dataser refer: https://archive.ics.uci.edu/dataset/477/real+estate+valuation+data+set
real_estate_dataset = pd.read_excel(r"C:\Users\Admin\Documents\ML_XL\dataR2.xlsx")
real_estate_dataset

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   
114   72  25.590000       82    2.820  0.570392  24.9600    33.750000   
115   86  27.180000      138   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  Classification  
0     7.99585  417.114               1  
1     4.06405  468.786               1  
2     9.27715  554.697               1  
3    12.76600  928.220               1  
4    10.57635  773.920               1  
..        ...      ...             ...  
111  10.96000  268.230               2  
112   7.32000  330.160               2  
113  10.33000  314.050               2  
114   3.27000  392.460               2  
115   4.35000   90.090               2  

[116 rows x 10 columns]

In [36]:
real_estate_dataset.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [37]:
real_estate_dataset.tail()

Age    BMI  Glucose  Insulin      HOMA  Leptin  Adiponectin  Resistin  \
111   45  26.85       92     3.33  0.755688   54.68        12.10     10.96   
112   62  26.84      100     4.53  1.117400   12.45        21.42      7.32   
113   65  32.05       97     5.73  1.370998   61.48        22.54     10.33   
114   72  25.59       82     2.82  0.570392   24.96        33.75      3.27   
115   86  27.18      138    19.91  6.777364   90.28        14.11      4.35   

      MCP.1  Classification  
111  268.23               2  
112  330.16               2  
113  314.05               2  
114  392.46               2  
115   90.09               2

In [51]:
#Code for Linear Regression here

x = real_estate_dataset.drop('Classification', axis=1)
y = real_estate_dataset['Classification']

In [55]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [56]:
model.predict(X)

array([1.23806005, 1.48091859, 1.43164923, 1.38762671, 1.52583608,
       1.55754613, 1.33326778, 1.762431  , 1.54731464, 1.36265097,
       1.42876244, 1.42946376, 1.44119541, 1.66659444, 1.38248603,
       1.57502067, 1.36024518, 1.45177693, 1.2297969 , 1.385135  ,
       1.37760036, 1.27268221, 1.40522823, 1.3511594 , 1.36365315,
       1.11712286, 1.35021409, 1.43130818, 1.3660694 , 1.25750207,
       1.46224235, 1.34379457, 1.34268428, 1.50138434, 1.25241422,
       1.17235986, 1.13348042, 1.8196554 , 1.67388241, 1.00372919,
       1.21447185, 1.50484168, 1.29078776, 1.29223173, 1.39850419,
       1.36049992, 1.41952184, 0.96791788, 1.33153127, 1.42207513,
       1.76461212, 1.34326383, 1.93671019, 1.56378106, 1.86073636,
       1.8146405 , 1.67672905, 1.74172665, 1.64490748, 1.53758617,
       1.71300138, 1.85743581, 1.52663226, 1.6987011 , 1.64083933,
       1.8444137 , 1.45704093, 1.67488695, 1.57973707, 1.95806315,
       1.60979271, 2.16392875, 1.80746801, 1.58197159, 2.01527